package com.w3villa.domain;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class Users  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String fullName;
     private String nickName;
     private String userPassword;
     private String isActive;
     private String userRole;
     private Date lastReset;
     private String createdBy;
     private Date createdDate;
     private String updatedBy;
     private Date updatedDate;
     private String isLoggedIn;
     private Integer secretQuestionId;
     private String secretAnswer;

    public Users() {
    }

    public Users(String email, String fullName, String nickName, String userPassword, String isActive, String userRole, Date lastReset, String createdBy, Date createdDate, String updatedBy, Date updatedDate, String isLoggedIn, Integer secretQuestionId, String secretAnswer) {
       this.email = email;
       this.fullName = fullName;
       this.nickName = nickName;
       this.userPassword = userPassword;
       this.isActive = isActive;
       this.userRole = userRole;
       this.lastReset = lastReset;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
       this.isLoggedIn = isLoggedIn;
       this.secretQuestionId = secretQuestionId;
       this.secretAnswer = secretAnswer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="email", unique=true, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="fullName", length=45)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    
    @Column(name="nickName", length=45)
    public String getNickName() {
        return this.nickName;
    }
    
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    
    @Column(name="userPassword", length=200)
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    
    @Column(name="isActive", length=1)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="userRole", length=45)
    public String getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastReset", length=19)
    public Date getLastReset() {
        return this.lastReset;
    }
    
    public void setLastReset(Date lastReset) {
        this.lastReset = lastReset;
    }

    
    @Column(name="createdBy", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdDate", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="updatedBy", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updatedDate", length=19)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="isLoggedIn", length=1)
    public String getIsLoggedIn() {
        return this.isLoggedIn;
    }
    
    public void setIsLoggedIn(String isLoggedIn) {
        this.isLoggedIn = isLoggedIn;
    }

    
    @Column(name="secretQuestionId")
    public Integer getSecretQuestionId() {
        return this.secretQuestionId;
    }
    
    public void setSecretQuestionId(Integer secretQuestionId) {
        this.secretQuestionId = secretQuestionId;
    }

    
    @Column(name="secretAnswer", length=200)
    public String getSecretAnswer() {
        return this.secretAnswer;
    }
    
    public void setSecretAnswer(String secretAnswer) {
        this.secretAnswer = secretAnswer;
    }




}


